/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utuJava */

#ifndef _Included_utuJava
#define _Included_utuJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utuJava
 * Method:    utuC
 * Signature: ([I[D[C)V
 */
JNIEXPORT void JNICALL Java_utuJava_utuC
  (JNIEnv *, jobject, jintArray, jdoubleArray, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
